version: "2"

services:

  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    env_file: dev.env

  webpack:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - "8080:8080"
    env_file: dev.env
    command: bundle exec bin/webpack-dev-server
