version: "2"

volumes:
  packages:

services:

  web:
    build: ./web
    volumes:
      - ./web:/app
      - packages:/packages
    ports:
      - "3000:3000"
    env_file: dev.env
    depends_on:
      - db

  webpack:
    build: ./web
    volumes:
      - ./web:/app
      - packages:/packages
    ports:
      - "8080:8080"
    env_file: dev.env
    command: bundle exec bin/webpack-dev-server

  db:
    image: postgres
